# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import nucleo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
                ('nivel', models.CharField(choices=[('ME', 'Mestrado'), ('DO', 'Doutorado'), ('MP', 'Mestrado Profissional'), ('DP', 'Doutorado Profissional'), ('PD', 'Pós-Doutorado')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Fomento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Bolsa/Fomento',
                'verbose_name_plural': 'Bolsas e Fomentos',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='LinhaPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Linha de Pesquisa',
                'verbose_name_plural': 'Linhas de Pesquisa',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresso', models.SmallIntegerField(verbose_name='Ano de Ingresso')),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('T', 'Concluída'), ('X', 'Trancada'), ('F', 'Falecimento'), ('J', 'Jubilamento')], default='M', max_length=1)),
                ('status_bolsa', models.CharField(choices=[('N', 'Nenhuma'), ('A', 'Ativa'), ('E', 'Lista de Espera'), ('F', 'Finalizada')], default='N', max_length=1)),
                ('dtquali', models.DateTimeField(blank=True, null=True, verbose_name='Data da Qualificação')),
                ('dtdefesa', models.DateTimeField(blank=True, null=True, verbose_name='Data da Defesa')),
                ('trancamento', models.DateField(blank=True, null=True, verbose_name='Data de Trancamento')),
                ('meses_previstos', models.IntegerField(default=24, verbose_name='Meses Previstos')),
                ('obs', models.TextField(verbose_name='Observações')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coorientacao', models.BooleanField(verbose_name='Coorientação')),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('F', 'Inativa')], max_length=1)),
            ],
            options={
                'verbose_name': 'Orientação',
                'verbose_name_plural': 'Orientações',
            },
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome completo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('id_lattes', models.CharField(blank=True, max_length=15, null=True)),
                ('situacao', models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='G', max_length=1)),
                ('professor', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Pesquisador(a)',
                'verbose_name_plural': 'Pesquisadores',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='PesquisadorFomento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtinicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('dtfim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('obs', models.TextField(verbose_name='Observações')),
                ('fomento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Fomento')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pesquisador')),
            ],
            options={
                'verbose_name_plural': 'Pesquisadores',
            },
        ),
        migrations.CreateModel(
            name='PesquisadorLinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanente', models.BooleanField(verbose_name='Permanente')),
                ('dtentrada', models.DateField(blank=True, null=True, verbose_name='Ingresso')),
                ('dtsaida', models.DateField(blank=True, null=True, verbose_name='Dt.Saída')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.LinhaPesquisa')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pesquisador')),
            ],
        ),
        migrations.CreateModel(
            name='PesquisadorProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pesquisador')),
            ],
            options={
                'verbose_name': 'Pesquisador do Projeto',
                'verbose_name_plural': 'Pesquisadores do Projeto',
            },
        ),
        migrations.CreateModel(
            name='PesquisadorTitulacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='G', max_length=1)),
                ('curso_extenso', models.CharField(max_length=200)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Instituicao')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pesquisador')),
            ],
            options={
                'verbose_name': 'Titulação do Pesquisador',
                'verbose_name_plural': 'Titulações do Pesquisador',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('cod_sucupira', models.CharField(max_length=20)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Instituicao')),
            ],
            options={
                'verbose_name': 'Programa de Pós Graduação',
                'verbose_name_plural': 'Programas de Pós Graduação',
            },
        ),
        migrations.CreateModel(
            name='ProjetoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.LinhaPesquisa')),
            ],
            options={
                'verbose_name': 'Projeto de Pesquisa',
                'verbose_name_plural': 'Projetos de Pesquisa',
            },
        ),
        migrations.AddField(
            model_name='pesquisadorprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ProjetoPesquisa'),
        ),
        migrations.AddField(
            model_name='orientacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='nucleo.Pesquisador'),
        ),
        migrations.AddField(
            model_name='orientacao',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='nucleo.Pesquisador'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='pesquisador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pesquisador'),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Programa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Programa'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('nucleo.pesquisador', nucleo.models.AlunoManager),
        ),
    ]
