# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetopesquisa',
            name='nome',
            field=models.CharField(default='A', max_length=200),
        ),
        migrations.AlterField(
            model_name='programa',
            name='cod_sucupira',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projetopesquisa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
