# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import nucleo.models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20190814_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('nucleo.pesquisador', nucleo.models.ProfessorManager),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='professor',
            field=models.BooleanField(default=False),
        ),
    ]
