# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import nucleo.models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20190814_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoLinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtentrada', models.DateField(blank=True, null=True, verbose_name='Ingresso')),
                ('dtsaida', models.DateField(blank=True, null=True, verbose_name='Dt.Saída')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorLinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanente', models.BooleanField(default=True)),
                ('dtentrada', models.DateField(blank=True, null=True, verbose_name='Ingresso')),
                ('dtsaida', models.DateField(blank=True, null=True, verbose_name='Dt.Saída')),
            ],
        ),
        migrations.RemoveField(
            model_name='pesquisadorlinha',
            name='linha',
        ),
        migrations.RemoveField(
            model_name='pesquisadorlinha',
            name='pesquisador',
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.CharField(max_length=60, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='fomento',
            name='descricao',
            field=models.CharField(max_length=60, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='linhapesquisa',
            name='descricao',
            field=models.CharField(max_length=120, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('E', 'Efetivada'), ('T', 'Trancada'), ('O', 'Óbito'), ('J', 'Jubilamento')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status_bolsa',
            field=models.CharField(choices=[('N', 'Nenhuma'), ('A', 'Ativa'), ('E', 'Lista de Espera'), ('C', 'Concluída')], default='N', max_length=1, verbose_name='Status da Bolsa'),
        ),
        migrations.AlterField(
            model_name='orientacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='nucleo.Aluno'),
        ),
        migrations.AlterField(
            model_name='orientacao',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='nucleo.Professor'),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='situacao',
            field=models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='G', max_length=1, verbose_name='Titulação'),
        ),
        migrations.AlterField(
            model_name='pesquisadortitulacao',
            name='curso_extenso',
            field=models.CharField(max_length=200, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projetopesquisa',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.DeleteModel(
            name='PesquisadorLinha',
        ),
        migrations.AddField(
            model_name='professorlinha',
            name='linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.LinhaPesquisa'),
        ),
        migrations.AddField(
            model_name='professorlinha',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Professor'),
        ),
        migrations.AddField(
            model_name='alunolinha',
            name='linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.LinhaPesquisa'),
        ),
    ]
