# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20190814_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno/Aluna', 'verbose_name_plural': 'Alunos/as'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor(a)', 'verbose_name_plural': 'Professores/as'},
        ),
        migrations.AddField(
            model_name='matricula',
            name='dtaprovacao',
            field=models.DateField(blank=True, null=True, verbose_name='Dt.Aprovação CD'),
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='ano',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='situacao',
            field=models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado'), ('1', 'Linha 1'), ('2', 'Linha 2')], default='G', max_length=1, verbose_name='Titulação'),
        ),
        migrations.AlterField(
            model_name='pesquisadortitulacao',
            name='tipo',
            field=models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado'), ('1', 'Linha 1'), ('2', 'Linha 2')], default='G', max_length=1),
        ),
    ]
