# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20190814_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisadorPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pesquisador')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Programa')),
            ],
            options={
                'verbose_name': 'Programa do Pesquisador',
                'verbose_name_plural': 'Programas do Pesquisador',
            },
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor(a) do Programa', 'verbose_name_plural': 'Professores/as do Programa'},
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('C', 'Concluída'), ('T', 'Trancada'), ('O', 'Óbito'), ('J', 'Jubilamento')], default='M', max_length=1),
        ),
    ]
