# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_auto_20190819_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
