# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-02 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_auto_20190928_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='id_funcional',
            field=models.CharField(blank=True, help_text='Id.na Universidade (DRE, etc)', max_length=15, null=True, verbose_name='Id.Externo'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('C', 'Concluída'), ('T', 'Trancada'), ('O', 'Óbito'), ('J', 'Jubilamento')], default='A', max_length=1),
        ),
    ]
