# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_auto_20191002_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisador',
            name='professor',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('C', 'Concluída'), ('T', 'Trancada'), ('B', 'Abandono'), ('O', 'Óbito'), ('J', 'Jubilamento')], default='A', max_length=1),
        ),
    ]
