# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_auto_20191003_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientacao',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('F', 'Inativa')], default='A', max_length=1),
        ),
    ]
