# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-22 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_auto_20191003_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('doi', models.URLField()),
                ('ano', models.SmallIntegerField()),
                ('pais', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Produção Acadêmica',
                'verbose_name_plural': 'Produção Acadêmica',
            },
        ),
        migrations.CreateModel(
            name='TipoProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('cod_externo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Produção Acadêmica',
                'verbose_name_plural': 'Tipos de Produção Acadêmica',
            },
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='email_alternativo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail alternativo'),
        ),
        migrations.AddField(
            model_name='projetopesquisa',
            name='proponente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail principal'),
        ),
        migrations.AddField(
            model_name='producao',
            name='pesquisador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pesquisador'),
        ),
        migrations.AddField(
            model_name='producao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.TipoProducao'),
        ),
    ]
