# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0012_auto_20191122_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='dtupdate',
            field=models.DateField(blank=True, null=True, verbose_name='Atualização Lattes'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='pais',
            field=models.CharField(max_length=20),
        ),
    ]
