# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-22 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0013_auto_20191122_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='titulo',
            field=models.TextField(verbose_name='Título'),
        ),
    ]
