# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_auto_20191122_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducao',
            name='cod_externo',
            field=models.CharField(max_length=40),
        ),
    ]
