# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0015_auto_20191122_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
    ]
