# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0001_initial'),
        ('nucleo', '0016_auto_20191122_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='periodico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualis.Periodico'),
        ),
        migrations.AddField(
            model_name='programa',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qualis.Area'),
        ),
    ]
