# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0019_matricula_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='dtconclusao',
            field=models.DateField(blank=True, help_text='Entrega da Tese/Dissertação', null=True, verbose_name='Dt.Conclusão'),
        ),
    ]
