# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-04 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0020_auto_20191223_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='id_cnpq',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
