# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0021_pesquisador_id_cnpq'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='atualizado',
            field=models.BooleanField(default=False, help_text='Sincronizado com o Lattes'),
        ),
    ]
