# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0022_pesquisador_atualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientacao',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Matricula'),
        ),
        migrations.AlterField(
            model_name='orientacao',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('C', 'Concluída'), ('X', 'Cancelada')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='id_cnpq',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='ID CNPQ'),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='id_lattes',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ID Lattes'),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativa'), ('I', 'Inativa')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='projetopesquisa',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
