# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-07 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0023_auto_20200106_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetopesquisa',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Situação'),
        ),
    ]
