# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-19 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0025_producao_sem_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], default='A', max_length=1),
        ),
    ]
