# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0027_auto_20200423_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='conta_sucupira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producao',
            name='ident_unico',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Identificador Interno'),
        ),
    ]
