# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0028_auto_20200425_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisadorNomeCitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_citacao', models.CharField(max_length=100, verbose_name='Nome na citação')),
            ],
            options={
                'verbose_name': 'Nome para Citação',
                'verbose_name_plural': 'Nomes para Citação',
            },
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='orcid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ORCID'),
        ),
        migrations.AddField(
            model_name='producao',
            name='titulo_artigo',
            field=models.TextField(blank=True, null=True, verbose_name='Título do Artigo'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='titulo',
            field=models.TextField(verbose_name='Descrição Completa'),
        ),
        migrations.AddField(
            model_name='pesquisadornomecitacao',
            name='pesquisador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pesquisador'),
        ),
    ]
