# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0030_producaoautor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='serie',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='producao',
            name='volume',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
