# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0031_auto_20200915_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='volume',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
