# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-09-15 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0032_auto_20200915_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='ident_unico',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Identificador Interno'),
        ),
    ]
