# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-09-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0033_auto_20200915_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
