# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-20 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0034_producao_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Discente'},
        ),
    ]
