# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0035_auto_20201020_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
