# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-26 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0036_auto_20201026_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='conta_sucupira',
            field=models.BooleanField(default=False, verbose_name='Contabilizado no Sucupira'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True),
        ),
    ]
