# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-11-03 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0038_auto_20201026_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='producaoautor',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='producaoautor',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pesquisador'),
        ),
    ]
