# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-11-06 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0039_auto_20201103_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='idioma',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='pais',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
