# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-11-07 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0040_auto_20201106_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='periodico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualis.Periodico'),
        ),
    ]
