# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-11-18 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0042_auto_20201117_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='situacao',
            field=models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='G', max_length=1, verbose_name='Titulação'),
        ),
        migrations.AlterField(
            model_name='pesquisadortitulacao',
            name='tipo',
            field=models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='G', max_length=1),
        ),
    ]
