# Generated by Django 3.2.18 on 2023-03-22 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0044_auto_20230321_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='gscholar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Google Scholar'),
        ),
        migrations.AddField(
            model_name='producao',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Comprovante'),
        ),
        migrations.AddField(
            model_name='producao',
            name='validacao',
            field=models.CharField(choices=[('I', 'Importado'), ('E', 'Editado'), ('V', 'Validado')], default='A', max_length=1, verbose_name='Validação'),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='id_lattes',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Lattes Alfa'),
        ),
        migrations.CreateModel(
            name='RelatorioAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('descr_bolsa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bolsa')),
                ('desenvolvimento', models.TextField(blank=True, null=True)),
                ('disciplinas', models.TextField(blank=True, null=True, verbose_name='Disciplinas cursadas')),
                ('grupo_estudo', models.TextField(blank=True, null=True, verbose_name='Grupos de Estudo ou Leitura')),
                ('grupo_pesquisa', models.TextField(blank=True, null=True, verbose_name='Participação em Grupos do Programa')),
                ('part_pesquisa', models.TextField(blank=True, null=True, verbose_name='Participação em Pesquisas do Programa')),
                ('part_extensao', models.TextField(blank=True, null=True, verbose_name='Participação em Atividades de Extensão')),
                ('part_outras', models.TextField(blank=True, null=True, verbose_name='Participação em outras atividades coletivas de pesquisa e/ou extensão')),
                ('part_discente', models.TextField(blank=True, null=True, verbose_name='Participação em Instâncias de Representação Discente')),
                ('part_movimento', models.TextField(blank=True, null=True, verbose_name='Participação em Coletivos e Movimentos da Universidade')),
                ('seminarios', models.TextField(blank=True, null=True, verbose_name='Seminários do Programa')),
                ('premios', models.TextField(blank=True, null=True, verbose_name='Prêmios e distinções')),
                ('outras_atividades', models.TextField(blank=True, null=True, verbose_name='Outras atividades que considerar relevantes')),
                ('status', models.CharField(choices=[('I', 'Não iniciado'), ('E', 'Em edição'), ('V', 'Validado'), ('A', 'Avaliado')], default='I', max_length=1)),
                ('aprovado', models.BooleanField(blank=True, null=True)),
                ('comentario_orientador', models.TextField(blank=True, null=True)),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.pesquisador')),
                ('tipo_bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.fomento')),
            ],
        ),
    ]
