# Generated by Django 3.2.18 on 2023-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0045_auto_20230322_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1)),
                ('dtregistro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='relatorioanual',
            name='hash_auth',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relatorioanual',
            name='ano',
            field=models.SmallIntegerField(),
        ),
    ]
