# Generated by Django 3.2.18 on 2023-03-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0046_auto_20230322_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioanual',
            name='hash_auth',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
