# Generated by Django 3.2.18 on 2023-04-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0047_alter_relatorioanual_hash_auth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatorioanual',
            options={'verbose_name': 'Relatório Anual', 'verbose_name_plural': 'Relatórios Anuais de Produção'},
        ),
        migrations.AlterModelOptions(
            name='resumoanual',
            options={'verbose_name': 'Resumo Anual', 'verbose_name_plural': 'Resumos Anuais'},
        ),
        migrations.AddField(
            model_name='relatorioanual',
            name='hash_apr',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
    ]
