# Generated by Django 3.2.18 on 2023-04-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0048_auto_20230402_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioanual',
            name='desenvolvimento',
            field=models.TextField(blank=True, null=True, verbose_name='Desenvolvimento'),
        ),
        migrations.AlterField(
            model_name='relatorioanual',
            name='status',
            field=models.CharField(choices=[('I', 'Não iniciado'), ('E', 'Em edição'), ('C', 'Em edição'), ('R', 'Em edição'), ('V', 'Validado'), ('A', 'Avaliado')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='relatorioanual',
            name='tipo_bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nucleo.fomento', verbose_name='Tipo de Bolsa'),
        ),
    ]
