# Generated by Django 3.2.18 on 2023-04-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0051_auto_20230412_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproducao',
            options={'ordering': ('descricao',), 'verbose_name': 'Tipo de Produção Acadêmica', 'verbose_name_plural': 'Tipos de Produção Acadêmica'},
        ),
        migrations.AddField(
            model_name='producao',
            name='doi_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producao',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='natureza_obra',
            field=models.CharField(blank=True, choices=[('O', 'Obra Única'), ('A', 'Anais'), ('C', 'Coleção'), ('L', 'Coletânea'), ('D', 'Dicionário'), ('E', 'Enciclopédia')], max_length=1, null=True, verbose_name='Natureza da obra'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.tipoproducao', verbose_name='Tipo de Produção'),
        ),
        migrations.AlterField(
            model_name='relatorioanual',
            name='aprovado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
