# Generated by Django 3.2.18 on 2023-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0052_auto_20230419_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioanual',
            name='sandwich_orientador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Orientador'),
        ),
    ]
