# Generated by Django 3.2.18 on 2023-05-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0052_auto_20230418_1105'),
        ('nucleo', '0053_relatorioanual_sandwich_orientador'),
    ]

    operations = [
    ]
