# Generated by Django 3.2.18 on 2023-06-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0025_alter_periodicoindicador_area'),
        ('nucleo', '0054_merge_20230530_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='id_cnpq',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='ID CNPQ'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='periodico',
            field=models.ForeignKey(blank=True, help_text='Preencha ao menos 5 caracteres ou o ISSN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualis.periodico'),
        ),
        migrations.AlterUniqueTogether(
            name='pesquisadorprograma',
            unique_together={('pesquisador', 'programa')},
        ),
        migrations.AlterUniqueTogether(
            name='professorlinha',
            unique_together={('professor', 'linha')},
        ),
    ]
