# Generated by Django 3.2.18 on 2023-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0055_auto_20230612_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='raca',
            field=models.CharField(choices=[('04', 'Amarela'), ('01', 'Branca'), ('05', 'Indígena'), ('03', 'Parda'), ('02', 'Preta'), ('99', 'Não declarada')], max_length=2, null=True, verbose_name='Raça/Cor'),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='nome',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome completo'),
        ),
    ]
