# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cod_capes', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Área',
            },
        ),
        migrations.CreateModel(
            name='GrandeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Grande Área',
                'verbose_name_plural': 'Grandes Áreas',
            },
        ),
        migrations.CreateModel(
            name='Periodico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de Referência')),
                ('issn', models.CharField(blank=True, db_index=True, max_length=9, null=True, verbose_name='ISSN')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('status', models.CharField(default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Periódico',
            },
        ),
        migrations.CreateModel(
            name='PeriodicoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualis', models.CharField(default='ND', max_length=2)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualis.Area')),
                ('periodico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualis.Periodico')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='grande_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualis.GrandeArea'),
        ),
    ]
