# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-09 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0002_auto_20191209_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconhecimento',
            name='cod_capes',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Cód.Capes'),
        ),
    ]
