# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-10 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0003_auto_20191209_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodico',
            name='nome',
            field=models.CharField(max_length=140, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='periodico',
            name='referencia',
            field=models.CharField(blank=True, help_text='Como o nome aparece nas referências bibliográficas', max_length=100, null=True, verbose_name='Nome de Referência'),
        ),
        migrations.AlterField(
            model_name='periodico',
            name='sistema',
            field=models.CharField(blank=True, help_text='Sistema de Gerenciamento do Períodico', max_length=10, null=True),
        ),
    ]
