# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-21 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0006_periodico_dtvalidacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cod_externo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cód.Externo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualis.Assunto')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificação',
            },
        ),
        migrations.CreateModel(
            name='PeriodicoAssunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualis.Assunto')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Esquema de Classificação',
                'verbose_name_plural': 'Esquemas de Classificação',
            },
        ),
        migrations.AlterField(
            model_name='periodico',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualis.AreaConhecimento'),
        ),
        migrations.AddField(
            model_name='periodicoassunto',
            name='periodico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualis.Periodico'),
        ),
        migrations.AddField(
            model_name='assunto',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualis.Schema'),
        ),
    ]
