# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-21 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0007_auto_20201021_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodico',
            name='pais',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
