# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-26 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0009_auto_20201025_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla'),
        ),
    ]
