# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0010_schema_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicoindicador',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualis.Assunto'),
        ),
    ]
