# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-11-03 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0012_auto_20201028_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicoissn',
            name='meio',
            field=models.CharField(choices=[('P', 'Impresso'), ('E', 'Eletrônico'), ('O', 'Outros')], default='O', max_length=1),
        ),
    ]
