# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-11-08 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0013_auto_20201103_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodico',
            name='issn',
            field=models.CharField(max_length=9, unique=True, verbose_name='ISSN-L'),
        ),
    ]
