# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-11-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0014_auto_20201108_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodico',
            name='qualis',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('C', 'C'), ('ND', 'ND'), ('NC', 'NC')], default='ND', max_length=2),
        ),
    ]
