# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-03-15 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0015_auto_20201117_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodico',
            name='google_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='periodico',
            name='google_h5',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Google H5'),
        ),
        migrations.AddField(
            model_name='periodico',
            name='google_h5m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Google H5M'),
        ),
    ]
