# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0016_auto_20210315_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodico',
            name='modelo_economico',
            field=models.CharField(blank=True, choices=[('D', 'Diamond'), ('A', 'APC'), ('T', 'Trancado'), ('P', 'Predatório')], max_length=1, null=True, verbose_name='Modelo Econômico'),
        ),
    ]
