# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-04-16 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0018_auto_20210416_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodico',
            name='citescore',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Citescore'),
        ),
        migrations.AddField(
            model_name='periodico',
            name='scopus_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='periodico',
            name='sjr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='SJR'),
        ),
    ]
