# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-04-17 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0019_auto_20210416_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodico',
            name='google_h5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Google H5'),
        ),
        migrations.AlterField(
            model_name='periodico',
            name='google_h5m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Google H5M'),
        ),
        migrations.AlterField(
            model_name='periodico',
            name='nome',
            field=models.CharField(max_length=400, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='periodico',
            name='sjr',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='SJR'),
        ),
    ]
