# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-04-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0021_auto_20210418_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodico',
            name='editora',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='periodico',
            name='scopus_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
