# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2023-02-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0022_auto_20210418_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodico',
            name='frequencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodico',
            name='historico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
