# Generated by Django 3.2.18 on 2023-06-12 16:50

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('qualis', '0024_auto_20230321_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicoindicador',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='schema', null=True, chained_model_field='schema',
                                                            on_delete=django.db.models.deletion.CASCADE, to='qualis.assunto'),
        ),
    ]
