# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-12 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailagendado',
            name='status',
            field=models.CharField(choices=[('A', 'Aguardando envio manual'), ('R', 'Re-enviando'), ('E', 'Erro ao enviar'), ('K', 'Enviado')], default='A', max_length=1),
        ),
    ]
