# Generated by Django 3.2.18 on 2023-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20191212_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProcessamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Convite ao Aluno'), (2, 'Convite ao Professor'), (3, 'Solicitação de correção')])),
                ('template_email', models.TextField(blank=True, null=True, verbose_name='Template do Email')),
            ],
        ),
    ]
